name: github-pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup mdBook
        uses: jontze/action-mdbook@v2
        with:
          use-linkcheck: false
          use-mermaid: true
          use-toc: false
          use-opengh: false
          use-admonish: false
          use-katex: false

      - name: Build mdBook
        run: mdbook build

      - name: Deploy mdBook
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
